const talukasData = {
    'Akola': ['Akola Taluka', 'Barshitakli', 'Akot', 'Balapur', 'Murtijapur', 'Patur', 'Telhara'],
    'Ahmednagar': ['Ahmednagar Taluka', 'Akole', 'Jamkhed', 'Karjat', 'Kopargaon', 'Nagar', 'Nevasa', 'Parner', 'Pathardi', 'Rahata', 'Rahuri', 'Sangamner', 'Shevgaon', 'Shrigonda', 'Shrirampur'],
    'Amravati': ['Amravati Taluka', 'Achalpur', 'Aran', 'Bhatkuli', 'Chandur Bazar', 'Chandur Railway', 'Chikhaldara', 'Daryapur', 'Dhamangaon Railway', 'Dharni', 'Morshi', 'Nandgaon Khandeshwar', 'Teosa', 'Warud'],
    'Aurangabad': ['Aurangabad Taluka', 'Gangapur', 'Kannad', 'Paithan', 'Phulambri', 'Sillod', 'Soegaon', 'Vaijapur'],
    'Beed': ['Beed Taluka', 'Ambejogai', 'Ashti', 'Georai', 'Kaij', 'Majalgaon', 'Parali', 'Patoda', 'Wadwani'],
    'Bhandara': ['Bhandara Taluka', 'Lakhandur', 'Lakhani', 'Mohadi', 'Pauni', 'Sakoli', 'Tumsar'],
    'Buldhana': ['Buldhana Taluka', 'Buldana', 'Chikhli', 'Deolgaon Raja', 'Jalgaon (Jamod)', 'Khamgaon', 'Lonar', 'Malkapur', 'Mehkar', 'Motala', 'Nandura', 'Shegaon', 'Sindkhed Raja'],
    'Chandrapur': ['Chandrapur Taluka', 'Ballarpur', 'Bhadravati', 'Brahmapuri', 'Chandrapur (City)', 'Chimur', 'Gondpipri', 'Korpana', 'Mul', 'Nagbhir', 'Pombhurna', 'Rajura', 'Sawali', 'Warora'],
    'Dhule': ['Dhule Taluka', 'Amalner', 'Chalisgaon', 'Dhule (City)', 'Dondaicha', 'Sakri', 'Shindkheda', 'Sindkhede'],
    'Gadchiroli': ['Gadchiroli Taluka', 'Aheri', 'Armori', 'Bhamragad', 'Chamorshi', 'Desaiganj (Vadasa)', 'Dhanora', 'Etapalli', 'Gadchiroli (City)', 'Kurkheda', 'Mulchera', 'Sironcha'],
    'Gondia': ['Gondia Taluka', 'Amgaon', 'Deori', 'Gondia (City)', 'Goregaon', 'Sadak Arjuni', 'Tiroda'],
    'Hingoli': ['Hingoli Taluka', 'Aundha (Nagnath)', 'Basmath', 'Hingoli (City)', 'Kalamnuri', 'Sengaon'],
    'Jalgaon': ['Jalgaon Taluka', 'Amalner', 'Bhadgaon', 'Bhusawal', 'Bodwad', 'Chalisgaon', 'Dharangaon', 'Erandol', 'Jalgaon (Jamod)', 'Jamner', 'Pachora', 'Parola', 'Raver', 'Yawal'],
    'Jalna': ['Jalna Taluka', 'Ambad', 'Badnapur', 'Bhokardan', 'Ghansawangi', 'Jafferabad', 'Jalna (City)', 'Mantha', 'Partur'],
    'Kolhapur': ['Kolhapur Taluka', 'Ajra', 'Bavda', 'Bhudargad', 'Chandgad', 'Gadhinglaj', 'Hatkangale', 'Karvir (City)', 'Kagal', 'Panhala', 'Radhanagari', 'Shahuwadi', 'Shirol'],
    'Latur': ['Latur Taluka', 'Ahmadpur', 'Ausa', 'Chakur', 'Deoni', 'Jalkot', 'Latur (City)', 'Renapur', 'Shirur Anantpal', 'Udgir'],
    'Mumbai City': ['Mumbai (City)', 'Mumbai(City)'],
    'Mumbai Suburban': ['Mumbai (Suburban)', 'Andheri', 'Borivali', 'Kurla', 'Malad'],
    'Nagpur': ['Nagpur Taluka', 'Hingna', 'Kamptee', 'Katol', 'Nagpur (City)', 'Narkhed', 'Parshiwani', 'Ramtek', 'Savner', 'Umred'],
    'Nanded': ['Nanded Taluka', 'Ardhapur', 'Bhokar', 'Biloli', 'Deglur', 'Dharmabad', 'Hadgaon', 'Himayatnagar', 'Kandhar', 'Kinwat', 'Loha', 'Mahoor', 'Mudkhed', 'Mukhed', 'Naigaon', 'Nanded (City)', 'Umri'],
    'Nandurbar': ['Nandurbar Taluka', 'Akkalkuwa', 'Akrani', 'Nandurbar (City)', 'Navapur', 'Shahada', 'Talode'],
    'Nashik': ['Nashik Taluka', 'Deola', 'Dindori', 'Igatpuri', 'Kalwan', 'Malegaon', 'Nandgaon', 'Nashik (City)', 'Niphad', 'Peint', 'Sinnar', 'Trimbak', 'Yevla'],
    'Osmanabad': ['Osmanabad Taluka', 'Bhum', 'Kalamb', 'Lohara', 'Osmanabad (City)', 'Paranda', 'Tuljapur', 'Umarga', 'Washi'],
    'Palghar': ['Palghar Taluka', 'Dahanu', 'Jawhar', 'Mokhada', 'Palghar', 'Talasari', 'Vada', 'Vasai', 'Vikramgad'],
    'Parbhani': ['Parbhani Taluka', 'Gangakhed', 'Jintur', 'Manwath', 'Parbhani (City)', 'Purna', 'Sailu', 'Sonpeth'],
    'Pune': ['Pune Taluka', 'Ambegaon', 'Baramati', 'Bhor', 'Daund', 'Haveli', 'Indapur', 'Junnar', 'Khed', 'Mawal', 'Mulshi', 'Pune (City)', 'Purandhar', 'Shirur', 'Velhe'],
    'Raigad': ['Raigad Taluka', 'Alibag', 'Karjat', 'Khalapur', 'Mahad', 'Mangaon', 'Mhasala', 'Murud', 'Panvel', 'Pen', 'Poladpur', 'Roha', 'Shrivardhan', 'Sudhagad', 'Tala', 'Uran'],
    'Ratnagiri': ['Ratnagiri Taluka', 'Chiplun', 'Dapoli', 'Guhagar', 'Khed', 'Lanja', 'Mandangad', 'Rajapur', 'Ratnagiri (City)', 'Sangmeshwar'],
    'Sangli': ['Sangli Taluka', 'Atpadi', 'Jat', 'Kadegaon', 'Kavathemahankal', 'Khanapur', 'Miraj', 'Palus', 'Shirala', 'Tasgaon', 'Walwa'],
    'Satara': ['Satara Taluka', 'Jaoli', 'Karad', 'Khandala', 'Khatav', 'Koregaon', 'Mahabaleshwar', 'Man', 'Patan', 'Phaltan', 'Satara (City)', 'Wai'],
    'Sindhudurg': ['Sindhudurg Taluka', 'Deogad', 'Dodamarg', 'Kankavli', 'Kudal', 'Malvan', 'Sawantwadi', 'Vaibhavvadi', 'Vengurla'],
    'Solapur': ['Solapur Taluka', 'Akkalkot', 'Barshi', 'Karmala', 'Madha', 'Malshiras', 'Mangalvedhe', 'Mohol', 'Pandharpur', 'Sangole', 'Solapur (City)'],
    'Thane': ['Thane Taluka', 'Ambernath', 'Bhiwandi', 'Kalyan', 'Murbad', 'Shahapur', 'Thane (City)', 'Ulhasnagar', 'Vasai', 'Vikramgad'],
    'Wardha': ['Wardha Taluka', 'Arvi', 'Ashti', 'Deoli', 'Hinganghat', 'Samudrapur', 'Seloo', 'Wardha (City)'],
    'Washim': ['Washim Taluka', 'Karanja', 'Malegaon', 'Mangrulpir', 'Manora', 'Risod', 'Washim (City)'],
    'Yavatmal': ['Yavatmal Taluka', 'Arni', 'Babulgaon', 'Darwha', 'Digras', 'Ghatanji', 'Kalamb', 'Kelapur', 'Mahagaon', 'Ner', 'Pandharkawada', 'Pusad', 'Ralegaon', 'Umarkhed', 'Wani', 'Yavatmal (City)'],


};
export { talukasData };